import { AddressMap } from "../types";
import { ChainId } from "../enums";

export const FACTORY_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0xae8b490cfeE5956925d81f8A729cF0C2f2C33ba4',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const ROUTER_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.RINKEBY]: '',
  [ChainId.ROPSTEN]: '0x34CB6629a08F234F72e9DC5bE0FB352e88824d24',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const MONEY_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '0x6B3595068778DD592e39A122f4f5a5cF09C90fE2',
  [ChainId.ROPSTEN]: '0xE366ECf71a1A3c57a79F58Cd6295437EE9B9B71D',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const FARMING_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0x816822D1AAfD3186873c702a96213fd41884BA38',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const STAKING_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0x2D3882b6451c93e0707bbF0C4F1F05EeB096afd5',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const TIME_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0xe7C693003B925633355759ACf6F3e6EAC4E0217d',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const MIGRATOR_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0x5ACdEa5DA498f0162c9d3f8174E05090F0024bc5',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const WETH_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0xA3B45B73067fd2282aAB67436747e9b310254EBd',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const BUYBACK_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0x8f9F1910f6fC071cC5D850AaA740F2C9795A1C9d',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
}

export const RESERVE_ADDRESS: { [chainId in ChainId]: string } = {
  [ChainId.MAINNET]: '',
  [ChainId.ROPSTEN]: '0x69a97d0092a43880210aFAe4e4971eb4DcC58f13',
  [ChainId.RINKEBY]: '',
  [ChainId.GÖRLI]: '',
  [ChainId.KOVAN]: '',
  [ChainId.FANTOM]: '',
  [ChainId.FANTOM_TESTNET]: '',
  [ChainId.MATIC]: '',
  [ChainId.MATIC_TESTNET]: '',
  [ChainId.XDAI]: '',
  [ChainId.BSC]: '',
  [ChainId.BSC_TESTNET]: '',
  [ChainId.ARBITRUM]: '',
  [ChainId.ARBITRUM_TESTNET]: '',
  [ChainId.MOONBEAM_TESTNET]: '',
  [ChainId.AVALANCHE]: '',
  [ChainId.AVALANCHE_TESTNET]: '',
  [ChainId.HECO]: '',
  [ChainId.HECO_TESTNET]: '',
  [ChainId.HARMONY]: '',
  [ChainId.HARMONY_TESTNET]: '',
  [ChainId.OKEX]: '',
  [ChainId.OKEX_TESTNET]: '',
  [ChainId.CELO]: '',
  [ChainId.PALM]: '',
  [ChainId.PALM_TESTNET]: ''
};


export const BENTOBOX_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const KASHI_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const MAKER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const HODL_SWAPPER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const HODL_MULTISWAPPER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const HODL_MULTI_EXACT_SWAPPER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const PEGGED_ORACLE_ADDRESS =
  "";

export const HODL_TWAP_0_ORACLE_ADDRESS =
  "";

export const HODL_TWAP_1_ORACLE_ADDRESS =
  "";

export const CHAINLINK_ORACLE_ADDRESS =
  "";

export const BORING_HELPER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const STOP_LIMIT_ORDER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: "",
  [ChainId.RINKEBY]: "",
  [ChainId.GÖRLI]: "",
  [ChainId.KOVAN]: "",
  [ChainId.FANTOM]: "",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "",
  [ChainId.BSC]: "",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.ARBITRUM]: "",
  [ChainId.ARBITRUM_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.CELO]: "",
  [ChainId.PALM]: "",
  [ChainId.PALM_TESTNET]: ""
};

export const ARCHER_ROUTER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: ""
};

export const MINICHEF_ADDRESS: AddressMap = {
  [ChainId.MATIC]: "",
  [ChainId.XDAI]: "",
  [ChainId.HARMONY]: ""
};

export const WETH9_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  [ChainId.ROPSTEN]: "0xA3B45B73067fd2282aAB67436747e9b310254EBd",
  [ChainId.RINKEBY]: "0xc778417E063141139Fce010982780140Aa0cD5Ab",
  [ChainId.GÖRLI]: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6",
  [ChainId.KOVAN]: "0xd0A1E359811322d97991E03f863a0C30C2cF029C",
  [ChainId.ARBITRUM]: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1",
  [ChainId.ARBITRUM_TESTNET]: "0xf8456e5e6A225C2C1D74D8C9a4cB2B1d5dc1153b",
  [ChainId.BSC]: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8",
  [ChainId.FANTOM]: "0x74b23882a30290451A17c44f4F05243b6b58C76d",
  [ChainId.MATIC]: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
  [ChainId.OKEX]: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8",
  [ChainId.HECO]: "0x64FF637fB478863B7468bc97D30a5bF3A428a1fD",
  [ChainId.HARMONY]: "0x6983D1E6DEf3690C4d616b13597A09e6193EA013",
  [ChainId.XDAI]: "0x6A023CCd1ff6F2045C3309768eAd9E68F978f6e1",
  [ChainId.AVALANCHE]: "0xf20d962a6c8f70c731bd838a3a388D7d48fA6e15"
};

export const WNATIVE_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: WETH9_ADDRESS[ChainId.MAINNET],
  [ChainId.ROPSTEN]: WETH9_ADDRESS[ChainId.ROPSTEN],
  [ChainId.RINKEBY]: WETH9_ADDRESS[ChainId.RINKEBY],
  [ChainId.GÖRLI]: WETH9_ADDRESS[ChainId.GÖRLI],
  [ChainId.KOVAN]: WETH9_ADDRESS[ChainId.KOVAN],
  [ChainId.ARBITRUM]: WETH9_ADDRESS[ChainId.ARBITRUM],
  [ChainId.ARBITRUM_TESTNET]: WETH9_ADDRESS[ChainId.ARBITRUM_TESTNET],
  [ChainId.FANTOM]: "0x21be370D5312f44cB42ce377BC9b8a0cEF1A4C83",
  [ChainId.FANTOM_TESTNET]: "0xf1277d1Ed8AD466beddF92ef448A132661956621",
  [ChainId.MATIC]: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270",
  [ChainId.MATIC_TESTNET]: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270",
  [ChainId.XDAI]: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d",
  [ChainId.BSC]: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
  [ChainId.BSC_TESTNET]: "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd",
  [ChainId.MOONBEAM_TESTNET]: "0xe73763DB808ecCDC0E36bC8E32510ED126910394",
  [ChainId.AVALANCHE]: "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7",
  [ChainId.AVALANCHE_TESTNET]: "0xd00ae08403B9bbb9124bB305C09058E32C39A48c",
  [ChainId.HECO]: "0x5545153CCFcA01fbd7Dd11C0b23ba694D9509A6F",
  [ChainId.HECO_TESTNET]: "0x5B2DA6F42CA09C77D577a12BeaD0446148830687",
  [ChainId.HARMONY]: "0xcF664087a5bB0237a0BAd6742852ec6c8d69A27a",
  [ChainId.HARMONY_TESTNET]: "0x7a2afac38517d512E55C0bCe3b6805c10a04D60F",
  [ChainId.OKEX]: "0x8F8526dbfd6E38E3D8307702cA8469Bae6C56C15",
  [ChainId.OKEX_TESTNET]: "0x2219845942d28716c0F7C605765fABDcA1a7d9E0",
  [ChainId.CELO]: "0x471EcE3750Da237f93B8E339c536989b8978a438",
  [ChainId.PALM]: "0xF98cABF0a963452C5536330408B2590567611a71"
};

export const MASTERCHEF_V2_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: ""
};

export const ENS_REGISTRAR_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
  [ChainId.GÖRLI]: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
  [ChainId.ROPSTEN]: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
  [ChainId.RINKEBY]: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
};

export const ZAPPER_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "",
  [ChainId.ROPSTEN]: ""
};

export const MERKLE_DISTRIBUTOR_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "0xcBE6B83e77cdc011Cc18F6f0Df8444E5783ed982",
  [ChainId.ROPSTEN]: "0x84d1f7202e0e7dac211617017ca72a2cb5e2b955"
};

export const MULTICALL2_ADDRESS: AddressMap = {
  [ChainId.MAINNET]: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696",
  [ChainId.ROPSTEN]: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696",
  [ChainId.RINKEBY]: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696",
  [ChainId.GÖRLI]: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696",
  [ChainId.KOVAN]: "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696",
  [ChainId.ARBITRUM]: "0xadF885960B47eA2CD9B55E6DAc6B42b7Cb2806dB",
  [ChainId.ARBITRUM_TESTNET]: "0xa501c031958F579dB7676fF1CE78AD305794d579",
  [ChainId.CELO]: "0x9aac9048fC8139667D6a2597B902865bfdc225d3",
  [ChainId.FANTOM]: "0x22D4cF72C45F8198CfbF4B568dBdB5A85e8DC0B5",
  [ChainId.FANTOM_TESTNET]: "",
  [ChainId.MATIC]: "0x02817C1e3543c2d908a590F5dB6bc97f933dB4BD",
  [ChainId.MATIC_TESTNET]: "",
  [ChainId.XDAI]: "0x67dA5f2FfaDDfF067AB9d5F025F8810634d84287",
  [ChainId.BSC]: "0xa9193376D09C7f31283C54e56D013fCF370Cd9D9",
  [ChainId.BSC_TESTNET]: "",
  [ChainId.MOONBEAM_TESTNET]: "",
  [ChainId.AVALANCHE]: "0xdDCbf776dF3dE60163066A5ddDF2277cB445E0F3",
  [ChainId.AVALANCHE_TESTNET]: "",
  [ChainId.HECO]: "0xdDCbf776dF3dE60163066A5ddDF2277cB445E0F3",
  [ChainId.HECO_TESTNET]: "",
  [ChainId.HARMONY]: "0xdDCbf776dF3dE60163066A5ddDF2277cB445E0F3",
  [ChainId.HARMONY_TESTNET]: "",
  [ChainId.OKEX]: "0xF4d73326C13a4Fc5FD7A064217e12780e9Bd62c3",
  [ChainId.OKEX_TESTNET]: "",
  [ChainId.PALM]: "0x0769fd68dFb93167989C6f7254cd0D766Fb2841F"
};
